# Generated by Django 3.1.14 on 2025-10-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='profiles/default.jpg', upload_to='profiles/'),
        ),
    ]
