# Generated by Django 3.1.14 on 2025-10-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20251009_0856'),
        ('users', '0002_auto_20251004_1229'),
    ]

    operations = [
    ]
