# Generated by Django 3.1.14 on 2025-11-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Адмін'), ('EMPLOYEE', 'Співробітник')], default='EMPLOYEE', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
