# Generated by Django 3.1.14 on 2025-10-09 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_project_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='predecessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followers', to='task_manager.task'),
        ),
    ]
